package com.succexa.onlineshopping.security.config;

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer;

public class SpringApplicationInitializer extends AbstractSecurityWebApplicationInitializer {}